services:
  - type: web
    name: dropbeam-backend
    env: node
    plan: free
    branch: main
    buildCommand: npm install
    startCommand: node server.js
    autoDeploy: true
    envVars:
      - key: CLIENT_URL
        value: https://dropbeam-rust.vercel.app
      - key: NODE_ENV
        value: production
      - key: EXPIRY_MINUTES
        value: "15"
      - key: UPLOADS_DIR
        value: /tmp/uploads
      - key: ADMIN_TOKEN
        value: "727218"
